# Generated by Django 4.1.2 on 2022-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_employment_skill_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
