# Generated by Django 4.1.2 on 2022-11-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_job_category_job_job_description_job_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobcategory'),
        ),
    ]
