# Generated by Django 4.1.2 on 2022-11-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_experience_remove_job_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='exper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exper'),
        ),
    ]
