# Generated by Django 4.1.2 on 2022-11-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_exper_job_exper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='exper',
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Exper',
        ),
    ]
